### ISSUE TITLE
Pppp..Port

### ISSUE THREAD

**Issue by midnightmadwalk** [midnightmadwalk/LemonJamsBot#1]
help !

![image](https://i.imgur.com/P7EyzOH.jpg)

![image](https://user-images.githubusercontent.com/71778799/107112796-553b8a00-6880-11eb-8a61-a7846bebf215.png)

heroku assigning them different port , 
userbot and socket will not connect.

**Comment by rojvv** [comment]
what do you mean by userbot and socket will not connect? you mean the userbot.py can't start the socket server?

**Comment by midnightmadwalk** [comment]
both started on different ports ...

**Comment by rojvv** [comment]
br

**Comment by rojvv** [comment]
meow
